# Generated by Django 2.1.7 on 2019-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_needs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_bank_event', models.CharField(max_length=100)),
                ('food_bank_description', models.CharField(max_length=500)),
                ('food_bank_date', models.DateTimeField(verbose_name='Event Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodbanks',
            name='food_bank_description',
        ),
        migrations.RemoveField(
            model_name='foodbanks',
            name='food_bank_event',
        ),
    ]
