# Generated by Django 2.1.7 on 2019-04-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_needs', '0002_foodbankevents_food_bank_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodBankEvents',
            new_name='FoodBankEvent',
        ),
    ]
