# Generated by Django 2.1.7 on 2019-04-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_needs', '0002_auto_20190414_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbanks',
            name='food_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodbankevents',
            name='food_bank_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodbanks',
            name='food_bank_name',
            field=models.CharField(max_length=100, verbose_name='Food Bank Name'),
        ),
    ]
