sudo: true
language: python
python:
- 3.6.1
before_install:
- sudo apt-get update -qq
- sudo iptables -A INPUT -s 162.222.72.0/21 -j ACCEPT
- sudo iptables -A INPUT -s 66.85.48.0/21 -j ACCEPT
- sudo iptables -A INPUT -s 185.94.24.0/22 -j ACCEPT
install:
- pip install django
- curl -L https://www.npmjs.com/install.sh | sh
- npm install -g qunit
lint:
- pipenv run flake8
script:
- python ./tests/unit_tests/travis_ci_builds_test.py
- qunit 'tests/unit_tests/js/*_test.js'
- python ./tests/functional/*_test.py
notifications:
  slack:
    secure: XyplTun0kKTAGM2uAeqL0y3vt7vyghOad/ZOQ/V9YOYj6Ij+s63bWS6ytk44diC6j48XhcCqQlwi7RDINNCASWY+JTY7n4POZju6SYjsOt9hwXFyFKT3GXr2vpG9jLs/21ohdS5JrsjqC0xa0B7uyVPRifDNVVY4kdKSZdurPzbpb8YmupE30uTZxi8ImokWd1832tbCYF4fH3pLGeLS97MkElgpw4YHTABnNy0kl5sNOkQJFsGDCDUHaPr4yVwRV7Wh0KN/kGv7SHxSKiyL8GWUde90uj5n7r7dcoulTT270yxl705cZxMEpHDvDPmeKSBeKORE/ZvaYdJ1IohL13PzgXmlqg5hmNwI0Q5DLSHEyaQ8x3gujhslR7jtRHSxelVzbunrBn7FpG3ULKx5yM8DknAyIbJBx6icyxHlDj1ERn0s4HLNHFqO41xNFC1vPfxynIJAdr1bYsl6LWqLeMQbJTqk61fZGD7gEo/sDTgUFvH/k9oMKefm4Pu7go7VTHjZsNkFFrHxmGAQH69lIgKSZ2tLKCEanvBjBijOLjREWan3zGsefZBqJTLvu8kY+5vm85SmOHHYsGbxiZx2GTa9WZ+GW5c6YXQfNtwNeNGImg/y6xMESr2nWUGP41VCL3e0KVGXsRYQhNHQB+6D9C9Ozgh5ZParx6hr01JVXmw=
addons:
  sauce_connect:
    username: "mfraser4"
    access_key:
      secure: "yvOSshbVHcHWRsZYeD5aPjGxxNy9JqsKYzpk5RdVTnDy9TIf3LDITgQhtXrpWVkBirs1HloJ7vWN4O2eI7ktgfDfnEnqnG51oREpZ7Sk00oir5nMCLkXZO/MSTTCdMiYtk87Fz4+GRlN8kLBQFXWZnGMCCUC3FB1JzC3f+M6B4FakTVL5BBYTm2KITQ/lnanGWy8xiqm+dN0ulHCRb3zG6m2gmRHK+4TuU5QyGzT2znWumG88Gs9tIq6NBYUUe8VGKOoB0kquWxSyclbav/MFlxN7qPt2BFl44TWq+0w6TkwW8Y0oTSOP4157ZC2kipKk7zn0z123mdlh33S+4xqre8vD5OKVEkSmR+ML6dhG+ndkJj5u1E3EdtvuNFu/4qHFzOYXO5pGbvEeN6AhacwZ6dWmEztx/LdTmbLWSGiRrsYjoZUs9m1NtB4r/oowU7JlAIEVsJvBt+4PMnFe2iPpvFMHabwD+6sPuudbFrouTHQPmidabvrM9hqrteThUx4XBpSRZVE0bCWzIJW9767WN2+DZZL/w8lloL1RfMFLz/KnY+cNzNtr1eVNrhZwAc2pXzJIrkRBe2Q23GisczDz77dhIcVQSep3T61I0Pnunniw6FyaAYQzttxNm0CCqDXhVC91iFr9+U2WyMJMjXzXGzIBljc9vw1zCULmFNc5bY="