sudo: true
language: python
python:
- 3.6.1
before_install:
- sudo apt-get update -qq
- sudo iptables -A INPUT -s 162.222.72.0/21 -j ACCEPT
- sudo iptables -A INPUT -s 66.85.48.0/21 -j ACCEPT
- sudo iptables -A INPUT -s 185.94.24.0/22 -j ACCEPT
install:
- pip install django
- curl -L https://www.npmjs.com/install.sh | sh
- npm install -g qunit
lint:
- pipenv run flake8
script:
- python ./tests/unit_tests/travis_ci_builds_test.py
- qunit 'tests/unit_tests/js/*_test.js'
- python ./tests/functional/*_test.py
notifications:
  slack:
    secure: XyplTun0kKTAGM2uAeqL0y3vt7vyghOad/ZOQ/V9YOYj6Ij+s63bWS6ytk44diC6j48XhcCqQlwi7RDINNCASWY+JTY7n4POZju6SYjsOt9hwXFyFKT3GXr2vpG9jLs/21ohdS5JrsjqC0xa0B7uyVPRifDNVVY4kdKSZdurPzbpb8YmupE30uTZxi8ImokWd1832tbCYF4fH3pLGeLS97MkElgpw4YHTABnNy0kl5sNOkQJFsGDCDUHaPr4yVwRV7Wh0KN/kGv7SHxSKiyL8GWUde90uj5n7r7dcoulTT270yxl705cZxMEpHDvDPmeKSBeKORE/ZvaYdJ1IohL13PzgXmlqg5hmNwI0Q5DLSHEyaQ8x3gujhslR7jtRHSxelVzbunrBn7FpG3ULKx5yM8DknAyIbJBx6icyxHlDj1ERn0s4HLNHFqO41xNFC1vPfxynIJAdr1bYsl6LWqLeMQbJTqk61fZGD7gEo/sDTgUFvH/k9oMKefm4Pu7go7VTHjZsNkFFrHxmGAQH69lIgKSZ2tLKCEanvBjBijOLjREWan3zGsefZBqJTLvu8kY+5vm85SmOHHYsGbxiZx2GTa9WZ+GW5c6YXQfNtwNeNGImg/y6xMESr2nWUGP41VCL3e0KVGXsRYQhNHQB+6D9C9Ozgh5ZParx6hr01JVXmw=
addons:
  sauce_connect:
    username: "mfraser4"
    access_key:
      secure: jf4gB/Mo5ZoitEe2z9tMBnT7CTc259S/te5ATaKxVAGJO+MXpB9VFblJesAv0N622Uak0tRAAwGLHSheDAqS/vK0+CE7ry3y3Vc1HsgXOgQdi4TYGT0U6XFo0sSgpnAyYWvu7+/GZT2IpghqrrqBEczq0XpTHnEtxcwa9fe34lStZvIYxc/KEwp7M8xIeKnscTO69333fG154fOMdrAQoFOinupvdJJ+ZfnURf88di8QLyJ4y1+2vpa4CAu1qNVtqCvFaQt5dW4bp9tRmZSsJIwa9Fam4cJn7aqR2ed4ZWnjRA8Eez0NlW8HTE9avlOvx3nVzW7wj409ZqJmOn3T8gsTmzR+tQbA6hyev7Uzp19SOI+NCBD6SmBvSl57xRDYnPzQef89hE3ICXyIfMNRojbB5JnnpNc23D6i14w4hV+QkzDMUq6f0aMTAjiTATUqlRQrgY1KOOGxALok/eDFADVfjSNITgkJtHVS07laRcs/gN4Z2QUdlxY06f1frGiDMDuk9CKIpD1FQMD/vCMxG6s79ldiVxIqJ+sZotpim3T284A6qE9bH9IoeBwDFR9OG2LeZEFgc+ITmTnHg/hRALVD/GnlLN70ZhxLMZtlF5elKKUpnP+sJHSEhaIgSgWQfSIV76DS198LzgVM3u47YF7X8wnFYNJf98FMCxTQy+o=